Default::Contents::Compress "gzip";
Dir::ArchiveDir ".";
Dir::CacheDir ".";
TreeDefault::Directory "pool/main";
TreeDefault::SrcDirectory "pool/main";
Default::Packages::Extensions ".udeb";
Default::Packages::Compress ". gzip xz";
Default::Sources::Compress ". gzip xz";
Default::Contents::Compress "xz";
Default::Translation::Compress ". gzip xz bzip2";
Default::LongDescription "true";

BinDirectory "pool/main" {

Packages "dists/bullseye/main/debian-installer/binary-arm64/Packages";
Contents "dists/bullseye/main/debian-installer/binary-arm64/Contents-arm64";

#BinOverride "dists/bullseye/main/debian-installer/binary-arm64/override.bullseye.main.debian-installer";

};
