APT::FTPArchive::Release::Origin "atzlinux"; 
APT::FTPArchive::Release::Codename "bullseye"; 
APT::FTPArchive::Release::Components "main contrib non-free non-free-firmware"; 
APT::FTPArchive::Release::Label "atzlinux"; 
APT::FTPArchive::Release::Architectures "amd64 arm64 riscv64 i386"; 
APT::FTPArchive::Release::Suite "bullseye-atz";
APT::FTPArchive::Release::Version "11.7.1";
