Dir::ArchiveDir ".";
Dir::CacheDir ".";
TreeDefault::Directory "pool/contrib";
TreeDefault::SrcDirectory "pool/contrib";
Default::Packages::Extensions ".deb";
Default::Packages::Compress ". gzip xz";
Default::Sources::Compress ". gzip xz";
Default::Contents::Compress "gzip";
Default::Translation::Compress ". gzip xz bzip2";
Default::LongDescription "false";

Tree "dists/bullseye" {
  Sections "contrib";
  Architectures "amd64 arm64 source";
};

// This is the same for the contrib section
BinDirectory "pool/contrib" {
        Sources "dists/bullseye/contrib/source/Sources";
}

