Dir::ArchiveDir ".";
Dir::CacheDir ".";
TreeDefault::Directory "pool/main";
TreeDefault::SrcDirectory "pool/main";
Default::Packages::Extensions ".deb";
Default::Packages::Compress ". gzip xz";
Default::Sources::Compress ". gzip xz";
Default::Contents::Compress "gzip";
Default::Translation::Compress ". gzip xz bzip2";
Default::LongDescription "false";

Tree "dists/bullseye" {
  Sections "main";
  Architectures "amd64 arm64 riscv64 i386 source";
//  Architectures "arm64 source";
};

// This is the same for the main section
BinDirectory "pool/main" {
        Sources "dists/bullseye/main/source/Sources";
}
BinDirectory "pool/main" {
        Packages "dists/bullseye/main/binary-arm64/Packages";
        Contents "dists/bullseye/main/Contents-arm64";
}
// BinDirectory "pool/main" {
   //     Packages "dists/bullseye/main/binary-amd64/Packages";
     //   Contents "dists/bullseye/main/Contents-amd64";
//}
