Dir::ArchiveDir ".";
Dir::CacheDir ".";
TreeDefault::Directory "pool/non-free-firmware";
TreeDefault::SrcDirectory "pool/non-free-firmware";
Default::Packages::Extensions ".deb";
Default::Packages::Compress ". gzip xz";
Default::Sources::Compress ". gzip xz";
Default::Contents::Compress "gzip";
Default::Translation::Compress ". gzip xz bzip2";
Default::LongDescription "false";

Tree "dists/bullseye" {
  Sections "non-free-firmware";
  Architectures "amd64 arm64 riscv64 source";
};

// This is the same for the non-free-firmware section
BinDirectory "pool/non-free-firmware" {
        Sources "dists/bullseye/non-free-firmware/source/Sources";
}

