version: '1.0'
name: branch-pipeline-livecd
displayName: LiveCD Build Pipeline
stages:
  - stage:
    name: compile
    displayName: 编译
    steps:
      - step: build@general_build
        name: build_livecd
        displayName: 构建 LiveCD
        commands:
          - cd isodvd/livecd
          - sudo ./build-livecd.sh --mirror huawei
        artifacts:
          - name: LIVECD_ARTIFACT
            path:
              - /tmp/livecd/*.iso
      - step: publish@general_artifacts
        name: publish_livecd_artifacts
        displayName: 上传 LiveCD 制品
        dependArtifact: LIVECD_ARTIFACT
        artifactName: livecd-output
        dependsOn: build_livecd
  - stage:
    name: release
    displayName: 发布
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: '发布 LiveCD'
        dependArtifact: livecd-output
        version: '1.0.0.0'
        autoIncrement: true
triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - .*
